jacobrs/SOEN341

client/modules/User/UserActions.js, client/modules/User/components/UserLoginForm/UserLoginForm.css, client/modules/User/components/UserLoginForm/UserLoginForm.js, client/modules/User/pages/UserLoginPage/UserLoginPage.js, client/routes.js
Added UserLoginForm - form includes email and password fields, login button, and link to registration page
Added UserLoginPage
=> Start to user login page

client/modules/User/components/UserRegistrationForm/UserRegistrationForm.js
Now the form fields can be accessed by `this.state.field_name`.
ex: `this.state.email` returns the current value of the email field
=> Bind the registration form fields

client/modules/User/components/UserRegistrationForm/UserRegistrationForm.js
Just added the student id field to the registration form html
=> registration_form: added studentId field

client/modules/App/App.js, client/modules/App/AppActions.js, client/modules/User/UserActions.js, client/modules/User/components/UserLoginForm/UserLoginForm.js, client/modules/User/components/UserRegistrationForm/UserRegistrationForm.js, client/modules/User/pages/UserLoginPage/UserLoginPage.js, client/modules/User/pages/UserRegistrationPage/UserRegistrationPage.js, package.json, server/controllers/user.controller.js, server/dummyData.js, server/routes/user.routes.js, server/server.js
[Create user API endpoints](https://github.com/jacobrs/SOEN341/issues/20)
- Created the user API endpoints (GET, POST, and DELETE)
- The registration form now submits the inputs to the database
- Eslint now autofixes most problems
- Database duplicate bug
- ~When submitting registration form the inputs don't clear.~
- Test the API endpoints
- Hash passwords
=> Added the users API endpoints #20

server/controllers/user.controller.js
Added RegEx check for student ID and email format
=> fix #45 Registration form validation

client/modules/App/App.js, client/modules/App/components/Header/Header.css, client/modules/App/components/Header/Header.js, client/modules/User/UserReducer.js
I added the nav bar and it only shows up when the user logs in,  We need to do some cleanup in UserReducer because I really needed to add a new boolean to get the nav bar to hide properly.  The way the json is set up for our store is very messy and all over the place atm.
I rather just be able to check whether user in our store is null or not as opposed to having an extra boolean but its not in the initial state and its added in a very weird place (data.user but data is an array?)
=> wip #40 - Added nav bar

appspec.yml, deploy/install_dependencies, deploy/pm2_kickstart.sh, deploy/start_app, deploy/stop_app, package.json
This is a stepping stone for issue #51 includes all the necessary files to automate the deployment and link HEAD as the commit to fetch.
=> CodeDeploy files

Intl/localizationData/en.js
wip #51: testing the continuous deployment hook and changed some intl values
=> Continuous Deployment

Intl/localizationData/en.js
wip #51: Another change to test code deploy
=> wip #51: Another change to test code deploy

Intl/localizationData/fr.js
complete #51: tested code deploy last pull request, this is a confirmation pull request and the french intl file has also been updated
=> CodeDeploy final Test Merge #51

client/modules/User/UserActions.js, client/modules/User/UserReducer.js, client/modules/User/__test__/apiLogin.spec.js, client/modules/User/__test__/apiRegistration.spec.js, server/controllers/user.controller.js, server/routes/user.routes.js
[Create UPDATE API User endpoint](https://github.com/jacobrs/SOEN341/issues/54)
- Created the update User API endpoint
- Made the reducers for the update users
- Fixed some linting issues
=> #54 create UPDATE API User endpoint

client/design/UserDashboard.css, client/design/UserDashboard.html
Changed the position of the links in the navigation bar to float to the right. Modified the site name on left. Added a placeholder for the sign-out link on the right.
=> #39 Modified navigation bar design

client/modules/User/components/FormComponents/Validator.js, client/modules/User/components/UserRegistrationForm/UserRegistrationForm.css, client/modules/User/components/UserRegistrationForm/UserRegistrationForm.js, package.json
There should be no dependency issues this time around. Don't forget to run npm install to add the new dependencies.
=> #48 Added registration validation

client/main.css, client/modules/App/components/Header/Header.css, client/modules/App/components/Header/Header.js
Global font size and family has been changed to accommodate sam's design so the login and registration page will look slightly different
=> fix #40 implement navbar design using React

client/modules/User/components/UserLoginForm/UserLoginForm.js
=> Fixed typo in loginform

client/modules/User/components/UserInfoComponent/UserInfoComponent.css, client/modules/User/components/UserInfoComponent/UserInfoComponent.js
Blue background color will change once the dashboard is implemented
=> Added sidebar component

.coveralls.yml, README.md, client/modules/User/components/UserInfoComponent/UserInfoComponent.js, client/modules/User/pages/UserDashboardPage/UserDashboardPage.js, graph.eps, package.json
Testing the coveralls code integrated. Updates need to be on master in order to verify. Coveralls badge should appear in READ.ME with information about the test coverage of our project.
=> #77 Coveralls Integration Into project

.coveralls.yml
added the service name in the coveralls yaml in an attempt to fix the coveralls badge.
=> wip #77, testing new coveralls yml

.travis.yml, package.json
=> Done #77: Testing

client/modules/App/components/Header/Header.js, client/modules/User/UserActions.js, client/modules/User/components/UserRegistrationForm/UserRegistrationForm.js, client/modules/User/components/UserStudyGroupForm/UserStudyGroupForm.css, client/modules/User/components/UserStudyGroupForm/UserStudyGroupForm.js, client/modules/User/pages/UserStudyGroupPage/UserStudyGroupPage.js, client/routes.js
1- Created the study group form
2- Added the necessary routing for the new form
3- Added a navbar button to allow the user to create study groups
3- Modified the registration form to prevent page refresh (makes the website faster)
The validation for the study group only requires the user to have every field filled out. No specific format is required for the group name, teacher name, course tag or description.
=> #97 #105 Study group form

client/modules/User/components/UserLoginForm/UserLoginForm.js
Simple fix that allows the user to press enter after typing his password to log in
=> #82 Enter now logs in user

client/modules/User/UserActions.js, client/modules/User/UserReducer.js, client/modules/User/components/UserInfoComponent/UserInfoComponent.css, client/modules/User/components/UserInfoComponent/UserInfoComponent.js, client/modules/User/components/UserUpdateForm/UserUpdateForm.js, client/modules/User/pages/UserEditInfoPage/UserEditInfoPage.js, client/routes.js, public/js/loader.js, server/controllers/user.controller.js
The user can now update his information.
On the profile component an edit button is available. Clicking it will redirect to a form that will allow to user to change his information.
=> #42 Profile Information Update

client/modules/User/UserActions.js, client/modules/User/components/UserStudyGroupForm/UserStudyGroupForm.js, client/modules/User/pages/UserStudyGroupPage/UserStudyGroupPage.js, client/store.js, server/controllers/studyGroup.controller.js, server/controllers/user.controller.js, server/models/user.js
When a study group is created, the new group is now assigned to the user who created it.
=> #111 Study group assignement

server/models/message.js, server/server.js, server/socketEvents.js, server/testChat.html
Improve API for chat messages and link socket.io with database. Test with '/testchat/'.
- Updated the socket event handlers
- Created an event/event handler to fetch the ten most recent messages from the database
- Created an event/event handler to save a new message to the database
- Chat API endpoints were manually tested using Postman
- socket.io was tested with the HTML page
=> fix #78 finished chat backend API and linked socket.io with database

client/modules/User/__test__/apiRegistration.spec.js
Testing added for login and logout. Tests increase coverage to 83%.
=> #104 AT: Increase Test Coverage

client/modules/User/UserActions.js, client/modules/User/components/UserStudyGroupComponent/UserStudyGroupComponent.js
Study group component links display group names given an array of user's study groups. 
Currently using mock data.
=> wip #79 Study group component display group names given array of user's study groups. 

client/modules/User/UserActions.js, client/modules/User/UserReducer.js, client/modules/User/components/ChatComponent/ChatComponent.css, client/modules/User/components/ChatComponent/ChatComponent.js, client/modules/User/components/UserInfoComponent/UserInfoComponent.js, client/modules/User/components/UserStudyGroupComponent/UserStudyGroupComponent.js, client/modules/User/pages/UserDashboardPage/UserDashboardPage.js, server/controllers/studyGroup.controller.js, server/controllers/user.controller.js, server/models/studyGroup.js, server/models/user.js, server/routes/studyGroup.routes.js, server/routes/user.routes.js
Currently blocked until the study groups become available in the users object.  For now we can merge what I have so far so we have something to show for sprint 4
=> wip #76 begin work on ChatComponent

client/modules/User/components/UserInfoComponent/UserInfoComponent.js, client/modules/User/components/UserStudyGroupComponent/UserStudyGroupComponent.css, client/modules/User/components/UserStudyGroupComponent/UserStudyGroupComponent.js
Links to chat component of each study group.
=> done #79 Component displays user's study groups

client/modules/User/UserActions.js, client/modules/User/UserReducer.js, client/modules/User/components/ChatComponent/ChatComponent.css, client/modules/User/components/ChatComponent/ChatComponent.js, client/modules/User/components/UserInfoComponent/UserInfoComponent.css, client/modules/User/components/UserInfoComponent/UserInfoComponent.js, client/modules/User/components/UserStudyGroupComponent/UserStudyGroupComponent.css, client/modules/User/pages/UserDashboardPage/UserDashboardPage.js, server/controllers/studyGroup.controller.js, server/controllers/user.controller.js, server/routes/studyGroup.routes.js, server/routes/user.routes.js
* Style changes to dashboard
* Added a modal to add new users to chat
* Added mini chat menu
* 👍
=> #127, #131 Add members

.travis.yml
Added mongod to travis so #66 can be completed.
=> #66 adding mongod to travis in services

client/modules/User/UserReducer.js
=> fix #76 Fix not being able to receive messages due to error in store

client/modules/User/UserActions.js, client/modules/User/components/UserRegistrationForm/UserRegistrationForm.js, client/modules/User/components/UserStudyGroupForm/UserStudyGroupForm.js
Submitting the group creation form or user registration form now redirects the user instead of staying on the form page.
=> #129 Redirecting on form submition

client/modules/User/UserActions.js
Page now refreshes after creating a study group
=> Page now refreshes after creating a study group
